### ISSUE TITLE
Cannot view complete UML state

### ISSUE THREAD

**Issue by willkill07** [mucsci-students/2024sp-420-LambdaLegion#59]
## TODO

* Update CLI to have a basic graphical way to visualize the diagram. (It sounds so easy when you put it like this)

## Links: 
- #84

## Actual Time: (in minutes or hours -- after completion

**Comment by pmccullough2204** [comment]
# TODO

* Update CLI to have a basic graphical way to visualize the diagram. (It sounds so easy when you put it like this)

**Comment by jldaggs** [comment]
duplicate bug
